name: 'Validate helm charts'
description: 'prevalidate helm chart template before its deployment; executes helm lint and helm template commands'
inputs:
  chart-path:
    description: 'Path to helm chart directory'
    required: true
    default: './helm'
  extra-args:
    description: 'Arguments to be appended to lint and template commands such as "--set global.env=dev"'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: validate helm chart
      shell: bash
      run: |
        helm version
        helm dependency update ${{ inputs.chart-path }}
        helm lint ${{ inputs.chart-path }} ${{ inputs.extra-args }}
        helm template ${{ inputs.chart-path }} ${{ inputs.extra-args }}
