name: 'Validate helm charts'
description: 'prevalidate helm chart template before its deployment; executes helm lint and helm template commands'
inputs:
  chart-path:
    description: 'Path to helm chart directory'
    required: true
    default: './helm'
  extra-args:
    description: 'Arguments to be appended to lint and template commands such as "--set global.env=dev"'
    required: true
    default: ''
  repo-name:
    description: 'Name of helm repository to be added'
    required: false
    default: ''
  repo-url:
    description: 'URL of helm repository to be added'
    required: false
    default: ''
  repo-username:
    description: 'helm repository username'
    required: false
    default: ''
  repo-password:
    description: 'helm repository password'
    required: false
    default: ''
runs:
  using: 'docker'
  image: '../helm.dockerfile'
  args:
    - validate
    - ${{ inputs.chart-path }}
    - ${{ inputs.extra-args }}
    - ${{ inputs.repo-name }}
    - ${{ inputs.repo-url }}
    - ${{ inputs.repo-username }}
    - ${{ inputs.repo-password }}
