name: 'Gradle command action'
description: 'standardizes the CLI flags for gradle'
inputs:
  args:
    description: 'command you want to execute. If omitted, gradle is set up without executing any tasks'
    required: false
  max-workers:
    description: 'max workers to allocate to gradle'
    required: true
    default: '2'
  max-heap:
    description: 'max heap to allocate to gradle'
    required: true
    default: '6g'
  build-root-directory:
    description: 'Path to the root directory of the build. Default is the root of the GitHub workspace.'
    required: true
    default: $GITHUB_WORKSPACE
runs:
  using: "composite"
  steps: 
    - uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: ${{ inputs.build-root-directory }}
        arguments: |
          --info
          --max-workers=${{ inputs.max-workers }}
          -Dorg.gradle.jvmargs=-Xmx${{ inputs.max-heap }}
          -Dorg.gradle.console=plain 
          --continue
          ${{ inputs.args }}
