name: 'Gradle command action'
description: 'standardizes the CLI flags for gradle'
inputs:
  args:
    description: 'command you want to execute'
    required: true
runs:
  using: "composite"
  steps: 
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          --info
          --max-workers=2
          -Dorg.gradle.jvmargs=-Xmx4g
          -Dorg.gradle.console=plain 
          --continue
          ${{ inputs.args }}
