name: Dependency Check
description: 'OWASP Dependency Check'

inputs:
  nvd-api-key:
    description: "NVD API Key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Dependency Check
      if: ${{ inputs.nvd-api-key == '' }}
      uses: hypertrace/github-actions/gradle@main
      with:
        args: dependencyCheckAggregate

    - name: Dependency Check
      if: ${{ inputs.nvd-api-key != '' }}
      uses: hypertrace/github-actions/gradle@main
      with:
        args: dependencyCheckAggregate -Dnvd.api.key=${{ inputs.nvd-api-key }}

    - name: Upload dependency check report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Dependency check report
        path: ${{github.workspace}}/build/reports

    - name: Upload dependency check report to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: ${{github.workspace}}/build/reports/dependency-check-report.sarif
